//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string PaymentID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentStatus { get; set; }
        public string OrderID { get; set; }
        public string ResellerID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Reseller Reseller { get; set; }
    }
}
